/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Carlos
 */
public class JFJacobi extends javax.swing.JFrame implements TableModelListener {

    JFDatos r = new JFDatos();

    // Definimos tres arreglos para guardar los datos de la tabla 
    
    double A[][]= new double[JFDatos.numFilasMatriz][JFDatos.numColumnasMatriz];
    double X[]= new double[JFDatos.numFilasMatriz];
    double C[]= new double[JFDatos.numFilasMatriz];
    double aux[]=new double[JFDatos.numFilasMatriz];
      double aux2[]=new double[JFDatos.numFilasMatriz];
       double aux3[]=new double[JFDatos.numFilasMatriz];
       //double errores[]=new double[JFDatos.numIteraciones-1];
      String MatrizF[][]= new String[JFDatos.numFilasMatriz][JFDatos.numIteraciones];
  
         
    /**
     * Creates new form JFMetJacobiU3MetNum
     */
    public JFJacobi() {
        initComponents();
        //Definir que la ventana aparezca desde el centro de la pantalla...
        setLocationRelativeTo(this);
        //Definimos las dimensiones de las tablas A, X y C (Vectores resultantes del problema)...
        String[] titulos = new String[JFDatos.numColumnasMatriz];
        for (int contador = 0; contador < JFDatos.numFilasMatriz; contador++) {

            titulos[contador] = "X" + (contador + 1);
        }
        String[] x = new String[1];
        x[0] = "X";
        String[] c = new String[1];
        c[0] = "C";

        frmTablaAbs modelo = new frmTablaAbs(r.datos, titulos);
        frmTablaAbs modelo2 = new frmTablaAbs(r.datos, x);
        frmTablaAbs modelo3 = new frmTablaAbs(r.datos, c);
        //DefaultTableModel  x = new DefaultTableModel(5,6);
        jTable1.setModel(modelo);
        jTable2.setModel(modelo2);
        jTable3.setModel(modelo3);
        
       jTable4.setModel(tabla);
        /*jTable1.setModel(new ValoreDe_Tabla('A',JFDatos.numFilasMatriz,JFDatos.numColumnasMatriz));
        jTable1.getModel().addTableModelListener(this);
        jTable2.setModel(new ValoreDe_Tabla('X',JFDatos.numFilasMatriz,1));
        jTable3.setModel(new ValoreDe_Tabla('C',JFDatos.numFilasMatriz,1));
        
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("MATRIZ A");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel5.setText("MATRIZ X(0)");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setText("MATRIZ  C");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosmodulometjacobi/Impresora-icon.png"))); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("RESULTADOS:");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursosmodulometjacobi/Captura.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(129, 129, 129))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        
        for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {

            for (int col = 0; col < JFDatos.numColumnasMatriz; col++) {
                    String  test= (String) jTable1.getValueAt(fil, col);
                this.A[fil][col]=Double.parseDouble(test); 
                System.out.print( this.A[fil][col]+ ", ");
                 // System.out.print( test+ ", ");
            }
            System.out.println();
        }
        System.out.println();

        for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {
                String  test= (String) jTable2.getValueAt(fil, 0);
                this.X[fil]=Double.parseDouble(test);
            System.out.print(this.X[fil] + ", ");
        }
          System.out.println();
        for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {
            String  test= (String)jTable3.getValueAt(fil,0);
            this.C[fil]= Double.parseDouble(test);
            System.out.print( this.C[fil]+ ", ");
        }
        System.out.println();
        System.out.println("----------------------");
     
      /*
       for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {
            System.out.print(  this.aux[fil]);
        }
       */
         System.out.println();
         
         
        /* for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {
              System.out.print(this.aux[fil]); 
        }
         this.aux2=this.aux;
          System.out.println("-------------------------------");
        aux3= met.multVect(A, aux2, C);
         
         for (int fil = 0; fil < JFDatos.numFilasMatriz; fil++) {
              System.out.print(this.aux3[fil]);  
        }
         
         
         System.out.println("-------------------------------");
         */
        
        // se asigna e manera horizontal
        // SOLO LO ENTIENDE EDUARDO XDXD
        // TODOS LOS DERECHOS RESERVADOS JAJAJA
        this.aux= met.multVect(A, X, C);
        this.aux2= met.multVect(A, X, C);
        for(int id= 0; id< JFDatos.numIteraciones; id++)
       {
         
             for(int pas= 0; pas <  JFDatos.numFilasMatriz; pas++)
             {
               this.aux3[pas]= this.aux[pas];
              // System.out.print( aux3[pas]  +" ," );  
                 /*This.aux2= met.multVect(A,this.aux, C);
              System.out.print( aux2[pas]  +" ," );
              */
                 this.MatrizF[pas][id]= String.valueOf(this.aux2[pas]);
                 // linea donde se imprimen los datos
                  System.out.print( aux2[pas]  +" ," );  
               // aux es el arreglo donde estan los datos calculados
             

               
            
             }
              
             this.aux2=  met.multVect(A, this.aux3, C);  
            // solo lo imprime de manera horizontal
              System.out.println();
       }
         System.out.println("------------");
         for(int id= 0; id< JFDatos.numFilasMatriz; id++)
       {
         
             for(int pas= 0; pas <  JFDatos.numIteraciones; pas++)
             {
               
             System.out.print(this.MatrizF[id][pas]+" | ");
             }
           System.out.println();
       }
        
         jTable4.setModel(new DefaultTableModel(MatrizF, tabla.generador('R',JFDatos.numFilasMatriz,JFDatos.numIteraciones) ));
        
          System.out.println("IMPRESION DE ERRORES-----");
         //error
        /** this.errores=met.CalcularError(this.A);
         for (int i=0; i<(JFPreDatoMetJacobiU3MetNum.numIteraciones-1); i++)
         {
         System.out.print(this.errores[i]+" ,");
         }
       **/
         //jTable4.setModel(new  DefaultTableModel);
        
        
      
          
          // TableColumn c=jTable4.getColumnModel().getColumn(1);
           
         
              /* JComboBox combo=new JComboBox(xd);        
             TableColumn c = jTable4.getColumnModel().getColumn(1);
              TableCellEditor tce= new DefaultCellEditor(combo);
                c.setCellEditor(tce);*/
         System.out.println();
       }
       
      
    
    
       
       
       
    
       catch (Exception ex)
               {
               
               JOptionPane.showMessageDialog(null, "HUBO UN ERROR AL PROCESAR LOS DATOS :("+ex);
               }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JFDatos ventana=new JFDatos();
        ventana.show();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFJacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFJacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFJacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFJacobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFJacobi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
        for (int contador = 0; contador < JFDatos.numFilasMatriz; contador++) {
            for (int contador1 = 0; contador1 < JFDatos.numColumnasMatriz; contador1++) {
                jTable1.setValueAt(jTable1.getValueAt(contador, contador1), contador, contador1);
            }
        }
    }
    JFDatos im = new JFDatos();
clsMetodos  met=new  clsMetodos ();
ValoreDe_Tabla tabla=new ValoreDe_Tabla('R',JFDatos.numFilasMatriz,JFDatos.numIteraciones);
}
